# Generated by Django 2.2.19 on 2021-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='tag name')),
                ('color', models.CharField(choices=[('Red', '#DC143C'), ('Green', '#00FF7F'), ('Violet', '#EE82EE')], max_length=16)),
                ('slug', models.SlugField(unique=True, verbose_name='tag slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['-name'],
            },
        ),
    ]
