# Generated by Django 2.2.19 on 2021-12-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#DC143C', 'Red'), ('#00FF7F', 'Green'), ('#EE82EE', 'Violet')], max_length=16),
        ),
    ]
