# Generated by Django 2.2.19 on 2022-01-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20211230_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe_name',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='recipes.Recipe'),
        ),
    ]
