# Generated by Django 2.2.19 on 2022-01-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220111_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='measure',
            new_name='amount',
        ),
    ]
