# Generated by Django 2.2.19 on 2022-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220111_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='recipe_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.Tag', verbose_name='tag'),
        ),
    ]
