# Generated by Django 2.2.19 on 2022-01-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220111_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
