# Generated by Django 2.2.19 on 2022-01-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220111_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe_name',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='recipes.Recipe'),
        ),
    ]
